### ISSUE TITLE
Implement a normalization "exception" list.

### ISSUE THREAD

**Issue by PhillipsOwen** [RENCI-AUTOMAT/Data_services#1]
Node and edge normalizations can fail due to various reasons. these failures are reviewed to determine a final disposition. the final disposition of normalization may be to exempt this normalization to create a failure again.

Implement a process where the failure reviews are captured and used for future normalization error exemptions.

These exemptions should be able to handle:
 - all entries with a specific CURIE prefix (e.g. "CARO:*")
 - specific entries (e.g. "BFO:0000002")
 - ignore entries that are role based (e.g. any CHEBI's that have a "chemical modulation" role with a "protein" object)

This process should also include a way to curate this list as datasets are processed and results reviewed.

**Comment by cbizon** [comment]
cc: @EvanDietzMorris

**Comment by cbizon** [comment]
The idea here is really to be able to curate and persist this information from build to build.  Potentially also across builds (i.e. some rules like ignore PATO might be used across all databases, but maybe "ignore all children of MONDO:123" should only be used in one database)

**Comment by cbizon** [comment]
And just noticed I don't think that the third bullet in the original issue is quite right.  It's not that it's role based, it's that we might want to ignore whole sections of an ontology.  Usually we would do that by saying "everything that's a subclass of CHEBI:123213".

For example, we have chemical identifier normalization, and chebi is chemical identifiers, but we sometimes find chebi identifiers that don't normalize.  Is that a normalization error?  No, because chebi contains more than just chemical identifiers.  For instance, there is a whole section of chebi that is different kinds of "roles" that a chemical might have.  They have chebi id's, but they're not structures, and we want to be able to say that if one of them doesn't normalize, we don't care.  

We could do that by getting all of them and adding them to the specific entries group, but it's cleaner just to say "anything that is a role in chebi" or rephrasing "everything that is a subclass of chebi:role". 

Another non-role-based example is in MONDO which contains a set of disease properties we don't care about, or in EFO which has anatomical terms that are not interesting.

**Comment by cbizon** [comment]
OBE
